const DEl_TASK = "DEL_TASK";
const ADD_TASK = "ADD_TASK";
const SELECT_TASK = "SELECT_TASK";
const CHANGE_MODE = "CHANGE_MODE";
const UPDATE_PROFILE_SETTING = "UPDATE_PROFILE_SETTING";
const CHANGE_DATA_USER = "CHANGE_DATA_USER";
const SET_SOCIAL_INFO = "SET_SOCIAL_INFO";
const HIDE_OR_SHOW_WIDGETS = "HIDE_OR_SHOW_WIDGETS";
const SEND_NOTIFICATIONS = "SEND_NOTIFICATIONS";
const SET_USER_AUTH = "SET_USER_AUTH";
const SET_PROJECTS_DATA = "SET_PROJECTS_DATA";
const SET_FILE = "SET_FILE";

export {
  DEl_TASK,
  ADD_TASK,
  SELECT_TASK,
  CHANGE_MODE,
  CHANGE_DATA_USER,
  UPDATE_PROFILE_SETTING,
  SET_SOCIAL_INFO,
  HIDE_OR_SHOW_WIDGETS,
  SEND_NOTIFICATIONS,
  SET_USER_AUTH,
  SET_PROJECTS_DATA,
  SET_FILE,
};
